config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  devise_for :users

  get 'vote/:id', to: 'votes#vote'

  
  resources :categories, only: %i[index show new create edit update]
  resources :reviews do
    resources :comments

  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :reviews, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action only: %i[show]

  def index
    @featured = Review.find(featured) if Review.exists?(id: featured)

    @categories = Category.all
  end

  def show
    @reviews = Category.find(params[:id]).reviews.order('id DESC')
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def featured
    highest = Vote.group(:review_id).order('count_id DESC').limit(1).count(:id)
    highest.keys.first
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories_display
    content = ''
    @categories.each do |category|
      next if category.reviews.empty?

      content << content_tag(:div, class: 'col-6 col-lg-3 p-0') do
        content_tag(:div, style: featured_img(category.reviews.last.image_url).to_s,
                          class: 'category-img-height background-img position-relative') do
          category_display_name(category) + category_display_link(category)
        end
      end
    end

    content.html_safe
  end

  def category_display_name(category)
    content_tag(:span,
                class: 'category-name position-absolute border-bottom border-3 border-warning fw-bolder pb-1') do
      link_to category.name, category_path(category.id), class: 'text-white text-decoration-none'
    end
  end

  def category_display_link(category)
    content_tag(:span, class: 'category-title position-absolute text-white') do
      link_to category.reviews.last.title, category.reviews.last, class: 'text-white text-decoration-none'
    end
  end

  def show_category
    count_image = 2
    format_ = 'image-first'

    content = ''

    @reviews.each do |review|
      case format_
      when 'image-first'
        content << category_image(review) + review_category(review)

        count_image -= 1
        format_ = 'details-first' if count_image.zero?
      when 'details-first'
        content << review_category(review) + category_image(review)

        count_image += 1
        format_ = 'image-first' if count_image == 2
      end
    end

    content.html_safe
  end

  def category_image(review)
    content_tag(:div, class: 'col-6 col-lg-3 p-0') do
      content_tag(:div, '#', style: featured_img(review.image_url).to_s,
                             class: 'category-img-height background-img position-relative')
    end
  end

  def review_category(review)
    content_tag(:div, class: 'col-6 col-lg-3 p-0 px-3 py-2 bg-light') do
      concat content_tag(:span, review.category.name,
                         class: 'border-bottom border-3 border-warning text-warning primary-color fw-bolder pb-1')

      concat category_title(review)

      concat content_tag(:p, review.text, class: 'text-truncate')

      concat link_to 'vote', "/vote/#{review.id}", class: 'btn primary-bg-color text-white'
    end
  end

  def category_title(review)
    content_tag(:h5, class: 'mt-2') do
      link_to review.title, review, class: 'text-dark text-decoration-none'
    end
  end
end

app/views/categories/_featured.html.erb
<section class="featured">
    <div style="<%= featured_img(@featured.image_url) %>" class="featured-img-height background-img position-relative">
      <div class="featured-item position-absolute">
        <h4 class="featured-heading fw-bolder">
         <%= link_to @featured.title, @featured, class: 'primary-color text-decoration-none' %>
        </h4>
        <p class="featured-snippet text-white"><%= @featured.text %></p>
      </div>
    </div>
</section>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new_review align-items-center d-flex flex-column">
<div class="field">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="actions mt-3">
    <%= form.submit "Add Category", class: 'form-control primary-bg-color' %>
  </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="sticky-top-padding">
   <%= flash_message %>

   <%= featured_review %>

  <section class="row categories">
    <%= categories_display %>
  </section>
</div>

app/views/categories/new.html.erb
<h3 class="text-center mt-3">New Category</h3>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
   <%= flash_message %>

<div class="sticky-top-padding">

  <section class="row categories">
    <%= show_category %>
  </section>

</div>