config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  devise_for :users

  get 'vote/:id', to: 'votes#vote'

  
  resources :categories, only: %i[index show new create edit update]
  resources :reviews do
    resources :comments

  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action only: %i[show]
  before_action :authenticate_user!

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.includes(:comments).find(params[:id])
  end

  def new
    @review = Review.new
  end

  def edit; end

  def create
    @review = current_user.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :text, :image, :category_id, :author)
  end
end

app/helpers/review_helper.rb
module ReviewHelper
  def show_comments
    content = ''
    @review.comments.each do |comment|
      content << content_tag(:div, class: 'card mt-3 p-2 comment') do
        concat content_tag(:p, comment.user.name, class: 'fw-bolder')
        concat content_tag(:p, comment.content)
        concat content_tag(:span, comment.created_at.strftime('%Y/%m/%d'))
      end
    end
    content.html_safe
  end
end

app/views/reviews/_comment.html.erb
            <%= form_with(model: [@review, @review.comments.build], local: true) do |form| %>

 <%= form.text_area :content, id: :comment_content, class: 'form-control mt-3 comment', placeholder: 'Add new Comment' %>
      <%= form.submit 'Comment', class: 'btn primary-bg-color mt-3 comment mb-3' %>
            <% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
    
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/new.html.erb
<h3 class="text-center mt-2">You just finish reading a book?</h3>
<h5 class="text-center"> Write a Review!</h5>
<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
    
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new_review align-items-center d-flex flex-column justify-content-between">

  <div class="field">
    <%= form.label :title, class: 'form-label'  %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control" %>
  </div>
  <div class="field">
   <%= form.label :image %>
  <%= form.file_field :image, required: true, class: 'form-control' %>
        </div>
         <div class="field">
        <%= form.collection_select :category_id, Category.all, :id, :name, {prompt: "Select Category"}, required: true, class: 'form-control' %>
    </div>
  <div>
    <%= form.submit 'Submit Review', class: 'form-control btn primary-bg-color'  %>
  </div>
<% end %>
<p class="text-center">
    <%= link_to 'click to add a new category here', new_category_path, class: 'primary-color text-decoration-none' %></p>

</div>

app/views/reviews/show.html.erb
<div class="sticky-top-padding container-md">
    <%= flash_message %>

  <section class="row mt-3">
    <div class="col-12">
      <h4 class="fw-bolder"> <%= @review.title %> </h4>
      <p>by <span class="fw-bolder"><%= @review.author.name %></span></p>

            <%= link_to 'vote', "/vote/#{@review.id}", class: 'btn primary-bg-color text-white mb-3' %>


      <div style="<%= featured_img(@review.image_url) %>" class="featured-img-height background-img position-relative mb-3">
      
      </div>

      <p><%= @review.text %></p>
    </div>
  </section>

   
  </div>


           <%= show_comments %>


<%= render :partial => 'comment' %>
   <%# </div> %>
</div>