config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  devise_for :users

  get 'vote/:id', to: 'votes#vote'

  
  resources :categories, only: %i[index show new create edit update]
  resources :reviews do
    resources :comments

  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
<div>
  <a class="navbar-brand footer-logo" href="#">
    R 0'cLoCk
        </a>
        </div>
        <div>
      <a href="">Privacy Policy Terms & Conditions</a>
      </div>
      <div>
      <p class="text-white">Copyright 2021, All right reserved</p>
      </div>
      <div>
      <a href="https://twitter.com/devgrachy"><i class="fa fa-twitter"></i></a>
     <a href="https://www.linkedin.com/in/ajanaku-temitope/"> <i class="fa fa-linkedin"></i></a>
      <a href="https://web.facebook.com/ajanaku.temitopegrace"><i class="fa fa-facebook"></i></a>
      <div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
				
    <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
  <div class="notification primary">
   <p class="notice"><%= notice %></p>
</div>
<% end %>
 <% if flash[:alert] %>
  <div class="notification danger">
       <p class="alert"><%= alert %></p>
  </div>
<% end %>
       <nav class="navbar navbar-expand-lg  static-top">
  <div class="container">
         <%= link_to 'R0cLoCk', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
                          <%= link_to 'Home', root_path, class: 'nav-link' %>

        </li>

      <li class="nav-item">
                <%= link_to 'Write a Review', new_review_path, class: 'nav-link' %>

      </li>
        <%= category_links(all_categories) %>

      </ul>

    </div>
     <% if user_signed_in? %>
                                     <strong class="button">    <%= current_user.name%></strong>
|
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                        <% else %>
                                                                        <%= link_to "Log In", new_user_session_path, class: "button is_primary" %>
|
            <%= link_to "Register", new_user_registration_path, class: "button is_primary" %> 
                                                <% end %>
  </div>
</nav>

    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>